buses/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from buses import views

urlpatterns = [
    path(
        route='',
        view=views.BusView.as_view(),
        name='list'
    ),
    path(
        route='<int:pk>',
        view=views.DetailBusView.as_view(),
        name='detalle'
    ),
    path(
        route='crear',
        view=views.CreateBusView.as_view(),
        name='crear'
    ),
    path(
        route='editar/<int:pk>',
        view=views.UpdateBusView.as_view(),
        name='editar'
    ),
    path(
        route='eliminar/<int:pk>',
        view=views.DeleteBusView.as_view(),
        name='eliminar'
    ),
    path(
        route='filtro/',
        view=views.busesFiltro,
        name='filtro'
    ),

]

destacame/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

""" Rutas Apps Views """
from destacame import views as local_views
from choferes import views as choferes_views
from buses import views as buses_views
from trayectos import views as trayectos_views
from pasajeros import views as pasajeros_views

urlpatterns = [
    
    path('choferes/', include(('choferes.urls', 'choferes'), namespace='choferes')),
    path('buses/', include(('buses.urls', 'buses'), namespace='buses')),
    path('trayectos/', include(('trayectos.urls', 'trayectos'), namespace='trayectos')),
    path('pasajeros/', include(('pasajeros.urls', 'pasajeros'), namespace='pasajeros')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trayectos/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from trayectos import views

urlpatterns = [
    path(
        route='',
        view=views.TrayectoView.as_view(),
        name='list'
    ),
    path(
        route='<int:pk>',
        view=views.DetailTrayectoView.as_view(),
        name='detalle'
    ),
    path(
        route='crear',
        view=views.CreateTrayectoView.as_view(),
        name='crear'
    ),
    path(
        route='editar/<int:pk>',
        view=views.UpdateTrayectoView.as_view(),
        name='editar'
    ),
    path(
        route='eliminar/<int:pk>',
        view=views.DeleteTrayectoView.as_view(),
        name='eliminar'
    ),
    path(
        route='asignar/<int:pk>',
        view=views.asignarHorario,
        name='asignar'
    ),
    path(
        route='horario/borrar/<int:trayecto>/<int:horario>',
        view=views.borrarHorario,
        name='borrar_horario'
    ),

]

trayectos/models.py
from django.db import models

# Create your models here.
class Trayecto(models.Model):

    ruta_salida = models.CharField(max_length=50)
    ruta_llegada = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

class TrayectoBuses(models.Model):

    hora_salida = models.CharField(max_length=50)
    hora_llegada = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    bus = models.ForeignKey(
        'buses.Bus',
        on_delete=models.CASCADE,
    ) 
    trayecto = models.ForeignKey(
        Trayecto,
        on_delete=models.CASCADE,
    ) 
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

trayectos/forms.py
"""Post forms."""

# Django
from django import forms

# Models
from trayectos.models import Trayecto, TrayectoBuses


class TrayectoForm(forms.ModelForm):

    class Meta:
        model = Trayecto
        fields = ('ruta_salida','ruta_llegada','descripcion')

class HorariosForm(forms.ModelForm):
    class Meta:

        model = TrayectoBuses
        fields = [
			'hora_salida',
			'hora_llegada',
			'descripcion',
			'bus',
			'trayecto',
		]

trayectos/views.py
# Django
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.template import loader, Context
# Forms
from trayectos.forms import TrayectoForm, HorariosForm

# Models
from trayectos.models import Trayecto, TrayectoBuses
from buses.models import Bus
from pasajeros.models import Pasajero

class TrayectoView(ListView):

    template_name = 'trayectos/index.html'
    model = Trayecto
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'trayectos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        trayectos = Trayecto.objects.all()
        totalTrayectos = trayectos.count()
        for trayecto in trayectos:
            horarios =  TrayectoBuses.objects.filter(trayecto = trayecto.pk)
            trayecto.prom =  round(Pasajero.objects.filter(trayecto_bus__in = horarios).count() / totalTrayectos, 2)
        context['trayectos'] = trayectos

        return context


class DetailTrayectoView(DetailView):

    model = Trayecto
    template_name = 'trayectos/view.html'

class CreateTrayectoView(CreateView):

    model = Trayecto
    form_class = TrayectoForm
    template_name = 'trayectos/create.html'
    success_url = reverse_lazy('trayectos:list')


class UpdateTrayectoView(UpdateView):

    model = Trayecto
    template_name = 'trayectos/update.html'
    form_class = TrayectoForm
    success_url = reverse_lazy('trayectos:list')

class DeleteTrayectoView(DeleteView):

    model = Trayecto
    form_class = TrayectoForm
    success_url = reverse_lazy('trayectos:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def asignarHorario(request,pk):
    trayecto = Trayecto.objects.get(id=pk)
    buses = Bus.objects.all()
    horariosAsigandos = TrayectoBuses.objects.filter(trayecto_id = pk)
    error_msg = False
    form = HorariosForm        
    if request.method == 'POST':
        cargado = TrayectoBuses.objects.filter(trayecto_id = pk,bus_id = request.POST['bus'] ).count()
        if cargado == 0:
            form = HorariosForm(request.POST)
            if form.is_valid():
                form.save()
        else:
            error_msg = "El Bus ya se encuentra asignado a un horario"

    contexto = {'form':form,
        'trayecto':trayecto,
        'buses':buses,
        'horariosAsigandos':horariosAsigandos,
        'error_msg': error_msg 
    }
    return render(request, 'trayectos/horarios.html', contexto)

def borrarHorario(request,trayecto,horario):
    TrayectoBuses.objects.get(id = horario).delete()
    return redirect('trayectos:asignar',trayecto)

templates/trayectos/create.html
{% extends "main.html" %}

{% block head_content %}
<title>Crear Trayecto</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Registrar Trayecto </h4>
        </div>
    </div>

    <div class="row">
        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
                <div class="input-field col s8">
                    <input id="ruta_salida" name="ruta_salida" type="text" class="validate">
                    <label for="ruta_salida">Ruta Salida</label>
                    <span class="red-text">{% for error in form.rut.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    <input id="ruta_llegada" name="ruta_llegada" type="text" class="validate">
                    <label for="ruta_llegada">Ruta Llegada</label>
                    <span class="red-text">{% for error in form.ruta_llegada.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    <input id="descripcion" name="descripcion" type="text" class="validate">
                    <label for="descripcion">Descripcion</label>
                    <span class="red-text">{% for error in form.descripcion.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="divider"></div>


            <button type="submit" class="btn btn-primary  mt-5" value="Save">Guardar</button>
            <a href="/trayectos" class="btn btn-primary  mt-2" >Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/trayectos/horarios.html
{% extends "main.html" %}

{% block head_content %}
<title>Trayecto</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Asignar Horarios</h4>
        </div>
    </div>

    <div class="row">

            {% if error_msg %}
            <span class="red-text">{{ error_msg }}</span>
            {% endif %}

        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
            

                <div class="input-field col s2">
                    <input id="descripcion" name="descripcion" type="text" class="validate">
                    <label for="descripcion">Descripcion</label>
                    <span class="red-text">{% for error in form.descripcion.errors %}{{ error }}{% endfor %}</span>
                </div>

                <div class="input-field col s2">
                    <input id="hora_llegada" name="hora_llegada" type="text" class="timepicker">
                    <label for="hora_llegada">Hora Salida</label>
                    <span class="red-text">{% for error in form.hora_llegada.errors %}{{ error }}{% endfor %}</span>
                </div>

                <div class="input-field col s2">
                    <input id="hora_salida" name="hora_salida" type="text" class="timepicker">
                    <label for="hora_salida">Hora Llegada</label>
                    <span class="red-text">{% for error in form.hora_salida.errors %}{{ error }}{% endfor %}</span>
                </div>

                <div class="input-field bus col s2">
                    <select name="bus" id="bus">
                        {% for bus in buses %}
                        <option value="{{ bus.pk }}">{{ bus.descripcion }}</option>
                        {% endfor %}
                    </select>
                    <label for="bus">Bus</label>
                    <span class="red-text">{% for error in form.bus.errors %}{{ error }}{% endfor %}</span>
                </div>

                <input id="trayecto" name="trayecto" type="hidden" value="{{ trayecto.pk }}">

                <div class="add col s2">
                    <button type="submit" class="btn btn-primary  mt-5" value="Save">Agregar</button>
                </div>
            </div>
            <div class="divider"></div>

            <h5>Horarios Asignados</h5>

            <table class="table table-bordered" id="tb-horarios">
                    <thead>
                        <tr>
                            <th>Hora Salida</th>
                            <th>Hora LLegada</th>
                            <th>Descripcion</th>
                            <th>Bus</th>
                            <th>Acciones</th>
                        </tr>
                        
                    </thead>
                    <tbody>
                        {% if horariosAsigandos %}
                        {% for horarioAsignado in horariosAsigandos %}
                            <tr>
                                <td>{{ horarioAsignado.hora_salida }}</td>
                                <td>{{ horarioAsignado.hora_llegada }}</td>
                                <td>{{ horarioAsignado.descripcion }}</td>
                                <td>{{ horarioAsignado.bus.descripcion }}</td>
                                
                                <td>
                                    <a class="btn btn-primary " href='{% url "trayectos:borrar_horario" trayecto.pk horarioAsignado.pk %}'>Borrar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        
                        {% else %}
                            <tr>
                                <td colspan="6">
                                    <h4>No hay registros de horarios asignados</h4>
                                </td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>    

            <a href="/trayectos" class="btn btn-primary  mt-2">Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/trayectos/index.html
{% extends "main.html" %}

{% block head_content %}
    <title>Destacame</title>
{% endblock%}

{% block container %}


        <div class="row">

            <div class="col s12">
                <h3>Listado Trayectos</h3>
            </div>

            <div class="col s12">
                <a href='{% url "trayectos:crear" %}' class="btn btn-primary  mt-2" >Registrar Trayecto</a>
            </div>
        </div>

        <div class="divider"></div>
        <div class="row">
            <table class="table table-bordered" id="tb-trayectos">
                <thead>
                    <tr>
                        <th>Ruta Salida</th>
                        <th>Ruta LLegada</th>
                        <th>Descripción</th>
                        <th>Promedio Pasajeros</th>
                        <th>Editado</th>
                        <th>Acciones</th>
                    </tr>
                    
                </thead>
                <tbody>
                    {% if object_list %}
                    {% for trayecto in trayectos %}
                    <tr>
                        <td>{{ trayecto.ruta_salida }}</td>
                        <td>{{ trayecto.ruta_llegada }}</td>
                        <td>{{ trayecto.descripcion }}</td>
                        <td>{{ trayecto.prom }} </td>
                        <td>{{ trayecto.modified }}</td>
                        
                        <td>
                            <a class="btn btn-primary" href='{% url "trayectos:editar" trayecto.pk %}'>Editar</a>
                            <a class="btn btn-primary " href='{% url "trayectos:asignar" trayecto.pk %}'>Horarios</a>
                            <a class="btn btn-danger btn-confirm" href='{% url "trayectos:eliminar" trayecto.pk %}'>Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                    {% else %}
                    <tr>
                        <td colspan="6">
                            <h4>No hay registros de trayectos</h4>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>           
        </div>

{% endblock %}

templates/trayectos/update.html
{% extends "main.html" %}

{% block head_content %}
<title>Editar Trayectoria</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Editar  Trayectoria</h4>
        </div>
    </div>

    <div class="row">
        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
                <!--<h1>{{ object.rut }}</h1>-->
                <div class="input-field col s8">                    
                    {{form.ruta_salida}}
                    <label for="ruta_salida">Ruta Salida</label>
                    <span class="red-text">{% for error in form.ruta_salida.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    {{form.ruta_llegada}}
                    <label for="ruta_llegada">Ruta Llegada</label>
                    <span class="red-text">{% for error in form.ruta_llegada.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    {{form.descripcion}}
                    <label for="descripcion">Descripcion</label>
                    <span class="red-text">{% for error in form.descripcion.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>


            <button type="submit" class="btn btn-primary  mt-5" value="Save">Guardar</button>
            <a href="/trayectos" class="btn btn-primary  mt-2" >Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/trayectos/view.html
{% extends "main.html" %}

{% block head_content %}
<title>Trayecto</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Trayecto {{ object.descripcion }}</h4>
        </div>
    </div>

    <div class="row">

        <table>
            <tr>
                <td>
                    Ruta Salida
                </td>
                <td>
                    {{ object.ruta_salida }}
                </td>
            </tr>

            <tr>
                <td>
                    Ruta Llegada
                </td>
                <td>
                    {{ object.ruta_llegada }}
                </td>
            </tr>

            <tr>
                <td>
                    Descripcion
                </td>
                <td>
                    {{ object.descripcion }}
                </td>
            </tr>

        </table>

        <a href="/trayectos" class="btn btn-primary  mt-2">Regresar</a>
        </form>
    </div>
{% endblock %}