buses/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from buses import views

urlpatterns = [
    path(
        route='',
        view=views.BusView.as_view(),
        name='list'
    ),
    path(
        route='<int:pk>',
        view=views.DetailBusView.as_view(),
        name='detalle'
    ),
    path(
        route='crear',
        view=views.CreateBusView.as_view(),
        name='crear'
    ),
    path(
        route='editar/<int:pk>',
        view=views.UpdateBusView.as_view(),
        name='editar'
    ),
    path(
        route='eliminar/<int:pk>',
        view=views.DeleteBusView.as_view(),
        name='eliminar'
    ),
    path(
        route='filtro/',
        view=views.busesFiltro,
        name='filtro'
    ),

]

destacame/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

""" Rutas Apps Views """
from destacame import views as local_views
from choferes import views as choferes_views
from buses import views as buses_views
from trayectos import views as trayectos_views
from pasajeros import views as pasajeros_views

urlpatterns = [
    
    path('choferes/', include(('choferes.urls', 'choferes'), namespace='choferes')),
    path('buses/', include(('buses.urls', 'buses'), namespace='buses')),
    path('trayectos/', include(('trayectos.urls', 'trayectos'), namespace='trayectos')),
    path('pasajeros/', include(('pasajeros.urls', 'pasajeros'), namespace='pasajeros')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'plugins/materialize/css/materialize.min.css' %}"  media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>

    <script type="text/javascript" src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

 <!--Let browser know website is optimized for mobile-->
 <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

    <nav>
        <div class="nav-wrapper  deep-purple darken-3">
          <a href="#" class="brand-logo">Destacame Viajes</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href='{% url "choferes:list" %}'>Choferes</a></li>
            <li><a href='{% url "buses:list" %}'>Buses</a></li>
            <li class=""><a href='{% url "trayectos:list" %}'>Trayectos</a></li>
            <li><a href='{% url "pasajeros:list" %}'>Pasajeros</a></li>
          </ul>
        </div>
      </nav>

    <div class="container mt-8 ">
        {% block container %}
        {% endblock%}
    </div>
    
    {% include "modals.html" %}

    <script type="text/javascript" src="{% static 'plugins/materialize/js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>    
    <script type="text/javascript" src="{% static 'js/pasajeros.js' %}"></script>    
    <script type="text/javascript" src="{% static 'js/modalsEvents.js' %}"></script>    
  
</body>
</html>

templates/modals.html
<!-- Modal Form -->
<div id="modal-form" class="modal">
    <div class="modal-content">
            <h4 class="modal-msg-title">Write your Title</h4>
            <p class="modal-msg-body">Write your body</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="form-modal-submit waves-effect waves-red btn-flat">Guardar</a>
        <a href="#!" class="form-modal-cancel waves-effect waves-green btn-flat">Cancelar</a>
    </div>
</div>

<!-- Modal Confirm Delete -->
<div id="modal-confirm" class="modal">
        <div class="modal-content">
                <h4 class="modal-msg-title">Eliminar Registro</h4>
                <p class="modal-msg-body">¿ Esta seguro que desea eliminar el registro?</p>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-confirm-submit waves-effect waves-red btn-flat">Eliminar</a>
            <a href="#!" class="form-modal-cancel waves-effect waves-green btn-flat">Cancelar</a>
        </div>
</div>

<!-- Modal Message -->
<div id="modal-msg" class="modal">
    <div class="modal-content">
        <h4 class="modal-msg-title">Write your Title</h4>
        <p class="modal-msg-body">Write your body</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Cerrar</a>
    </div>
</div>