buses/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from buses import views

urlpatterns = [
    path(
        route='',
        view=views.BusView.as_view(),
        name='list'
    ),
    path(
        route='<int:pk>',
        view=views.DetailBusView.as_view(),
        name='detalle'
    ),
    path(
        route='crear',
        view=views.CreateBusView.as_view(),
        name='crear'
    ),
    path(
        route='editar/<int:pk>',
        view=views.UpdateBusView.as_view(),
        name='editar'
    ),
    path(
        route='eliminar/<int:pk>',
        view=views.DeleteBusView.as_view(),
        name='eliminar'
    ),
    path(
        route='filtro/',
        view=views.busesFiltro,
        name='filtro'
    ),

]

destacame/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

""" Rutas Apps Views """
from destacame import views as local_views
from choferes import views as choferes_views
from buses import views as buses_views
from trayectos import views as trayectos_views
from pasajeros import views as pasajeros_views

urlpatterns = [
    
    path('choferes/', include(('choferes.urls', 'choferes'), namespace='choferes')),
    path('buses/', include(('buses.urls', 'buses'), namespace='buses')),
    path('trayectos/', include(('trayectos.urls', 'trayectos'), namespace='trayectos')),
    path('pasajeros/', include(('pasajeros.urls', 'pasajeros'), namespace='pasajeros')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buses/models.py
from django.db import models

# Create your models here.

class Bus(models.Model):

    descripcion = models.CharField(max_length=15)
    chofer = models.ForeignKey(
        'choferes.Chofer',
        on_delete=models.CASCADE,
    )   
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

buses/forms.py
"""Post forms."""

# Django
from django import forms

# Models
from buses.models import Bus


class BusForm(forms.ModelForm):

    class Meta:
        model = Bus
        fields = ('descripcion','chofer')

buses/views.py
# Create your views here.

# Django
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.template import loader, Context
# Forms
from buses.forms import BusForm
from choferes.forms import ChoferForm

# Models
from buses.models import Bus
from choferes.models import Chofer
from trayectos.models import TrayectoBuses, Trayecto
from pasajeros.models import Pasajero


class BusView(ListView):

    template_name = 'buses/index.html'
    model = Bus
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'buses'


class DetailBusView(DetailView):

    model = Bus
    template_name = 'buses/view.html'

class CreateBusView(CreateView):

    model = Bus
    form_class = BusForm
    template_name = 'buses/create.html'
    success_url = reverse_lazy('buses:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chofer'] = Chofer.objects.all()
        return context
 


class UpdateBusView(UpdateView):

    model = Bus
    template_name = 'buses/update.html'
    form_class = BusForm
    success_url = reverse_lazy('buses:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chofer'] = Chofer.objects.all()
        return context

class DeleteBusView(DeleteView):

    model = Bus
    form_class = BusForm
    success_url = reverse_lazy('buses:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def busesFiltro(request):
    buses = Bus.objects.all()
    for bus in buses:
            horarios =  TrayectoBuses.objects.filter(bus = bus.pk)
            cantBoletos =  Pasajero.objects.filter(trayecto_bus__in = horarios).count()
            bus.vendido = True if cantBoletos >= 1 else False

    return render(request, 'buses/filter.html', {'buses':buses})

templates/buses/create.html
{% extends "main.html" %}

{% block head_content %}
<title>Crear Trayectoria</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Registrar Bus</h4>
        </div>
    </div>

    <div class="row">
        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
                <div class="input-field col s8">
                    <input id="descripcion" name="descripcion" type="text" class="validate">
                    <label for="descripcion">Descripcion</label>
                    <span class="red-text">{% for error in form.descripcion.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                    <div class="input-field col s12">
                            <select name="chofer" id="chofer">
                            {% for chofer in chofer %}
                              <option value="{{ chofer.pk }}">{{ chofer.nombre }}</option>
                            {% endfor %}  
                            </select>
                            <label for="chofer">Conductor Asignado</label>
                            <span class="red-text">{% for error in form.chofer_id.errors %}{{ error }}{% endfor %}</span>
                          </div>
            </div>

            <button type="submit" class="btn btn-primary  mt-5" value="Save">Guardar</button>
            <a href="/buses" class="btn btn-primary  mt-2" >Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/buses/filter.html
{% extends "main.html" %}

{% block head_content %}
<title>Buses</title>
{% endblock%}

{% block container %}

    <div class="row">

        <div class="col s12">
            <h3>Listado Buses Con Pasajes Vendidos</h3>
        </div>

        <div class="col s12">
            <a href='{% url "buses:crear" %}' class="btn btn-primary  mt-2">Registrar Bus</a>
            <a href='{% url "buses:list" %}' class="btn btn-primary  mt-2">Todos los Buses</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Descripcion</td>
                    <td>Chofer</td>
                    <td>Editado</td>
                    <td>Acciones</td>
                </tr>

            </thead>
            <tbody>
                {% if buses %}
                {% for bus in buses %}
                {% if bus.vendido %}
                <tr>
                    <td>{{ bus.descripcion }}</td>
                    <td>{{ bus.chofer.nombre }}</td>
                    <td>{{ bus.modified }}</td>
                    <td>
                            <a class="btn btn-primary " href='{% url "buses:detalle" bus.pk %}'>Ver</a>
                            <a class="btn btn-primary" href='{% url "buses:editar" bus.pk %}'>Editar</a>
                            <a class="btn btn-danger btn-confirm" href='{% url "buses:eliminar" bus.pk %}'>Eliminar</a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}

                {% else %}
                <tr>
                    <td colspan="6">
                        <h4>No hay registros de solicitudes</h4>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/buses/index.html
{% extends "main.html" %}

{% block head_content %}
<title>Buses</title>
{% endblock%}

{% block container %}

    <div class="row">

        <div class="col s12">
            <h3>Listado Buses</h3>
        </div>

        <div class="col s12">
            <a href='{% url "buses:crear" %}' class="btn btn-primary  mt-2">Registrar Bus</a>
            <a href='{% url "buses:filtro" %}' class="btn btn-primary  mt-2">Filtrar Buses</a>
        </div>
    </div>
    <div class="row">
        <table class="mdl-data-table" id="tb-buses">
            <thead>
                <tr>
                    <td>Descripción</td>
                    <td>Chofer</td>
                    <td>Editado</td>
                    <td>Acciones</td>
                </tr>

            </thead>
            <tbody>
                {% if buses %}
                {% for bus in buses %}
                <tr>
                    <td>{{ bus.descripcion }}</td>
                    <td>{{ bus.chofer.nombre }}</td>
                    <td>{{ bus.modified }}</td>
                    <td>
                            <a class="btn btn-primary " href='{% url "buses:detalle" bus.pk %}'>Ver</a>
                            <a class="btn btn-primary" href='{% url "buses:editar" bus.pk %}'>Editar</a>
                            <a class="btn btn-danger btn-confirm" href='{% url "buses:eliminar" bus.pk %}'>Eliminar</a>
                    </td>
                </tr>
                {% endfor %}

                {% else %}
                <tr>
                    <td colspan="6">
                        <h4>No hay registros de buses</h4>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/buses/update.html
{% extends "main.html" %}

{% block head_content %}
<title>Editar Bus</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Editar Bus</h4>
        </div>
    </div>

    <div class="row">
        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
                <div class="input-field col s8">
                    {{form.descripcion}}
                    <label for="descripcion">Descripcion</label>
                    <span class="red-text">{% for error in form.descripcion.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                    <div class="input-field col s12">
                            <select name="chofer" id="chofer">
                            {% for chofer in chofer %}
                              <option value="{{ chofer.pk }}" {% if object.chofer.pk == chofer.pk %} selected  {% endif %}>{{ chofer.nombre }}</option>
                            {% endfor %}  
                            </select>
                            <label for="chofer">Conductor Asignado</label>
                            <span class="red-text">{% for error in form.chofer_id.errors %}{{ error }}{% endfor %}</span>
                    </div>
            </div>

            <button type="submit" class="btn btn-primary  mt-5" value="Save">Guardar</button>
            <a href="/buses" class="btn btn-primary  mt-2" >Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/buses/view.html
{% extends "main.html" %}

{% block head_content %}
<title>Choferes</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Perfil Bus {{ object.descripcion }}</h4>
        </div>
    </div>

    <div class="row">

        <table>
            <tr>
                <td>
                    Descripcion
                </td>
                <td>
                    {{ object.descripcion }}
                </td>
            </tr>

            <tr>
                <td>
                    Conductor
                </td>
                <td>
                    {{ object.chofer.nombre }}
                </td>
            </tr>

            <tr>
                <td>
                    Modificado
                </td>
                <td>
                    {{ object.modified }}
                </td>
            </tr>

            <tr>
                <td>
                    Creado
                </td>
                <td>
                    {{ object.created }}
                </td>
            </tr>
        </table>

        <a href="/buses" class="btn btn-primary  mt-2">Regresar</a>
        </form>
    </div>
{% endblock %}