buses/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from buses import views

urlpatterns = [
    path(
        route='',
        view=views.BusView.as_view(),
        name='list'
    ),
    path(
        route='<int:pk>',
        view=views.DetailBusView.as_view(),
        name='detalle'
    ),
    path(
        route='crear',
        view=views.CreateBusView.as_view(),
        name='crear'
    ),
    path(
        route='editar/<int:pk>',
        view=views.UpdateBusView.as_view(),
        name='editar'
    ),
    path(
        route='eliminar/<int:pk>',
        view=views.DeleteBusView.as_view(),
        name='eliminar'
    ),
    path(
        route='filtro/',
        view=views.busesFiltro,
        name='filtro'
    ),

]

choferes/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from choferes import views

urlpatterns = [
    path(
        route='',
        view=views.ChoferesView.as_view(),
        name='list'
    ),
    path(
        route='<int:pk>',
        view=views.DetailChoferView.as_view(),
        name='detalle'
    ),
    path(
        route='create',
        view=views.CreateChoferView.as_view(),
        name='crear'
    ),
    path(
        route='editar/<int:pk>',
        view=views.UpdateChoferView.as_view(),
        name='editar'
    ),
    path(
        route='eliminar/<int:pk>',
        view=views.DeleteChoferView.as_view(),
        name='eliminar'
    ),

]

destacame/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

""" Rutas Apps Views """
from destacame import views as local_views
from choferes import views as choferes_views
from buses import views as buses_views
from trayectos import views as trayectos_views
from pasajeros import views as pasajeros_views

urlpatterns = [
    
    path('choferes/', include(('choferes.urls', 'choferes'), namespace='choferes')),
    path('buses/', include(('buses.urls', 'buses'), namespace='buses')),
    path('trayectos/', include(('trayectos.urls', 'trayectos'), namespace='trayectos')),
    path('pasajeros/', include(('pasajeros.urls', 'pasajeros'), namespace='pasajeros')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

choferes/models.py
from django.db import models

# Create your models here.

class Chofer(models.Model):

    rut = models.IntegerField(max_length=15)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

choferes/forms.py
"""Post forms."""

# Django
from django import forms

# Models
from choferes.models import Chofer


class ChoferForm(forms.ModelForm):

    class Meta:
        model = Chofer
        fields = ('rut', 'nombre', 'apellido', 'telefono')

choferes/views.py
# Create your views here.

# Django
from django.shortcuts import render
from django.urls import reverse_lazy
#from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.template import loader, Context

# Forms
#from posts.forms import PostForm
from choferes.forms import ChoferForm

# Models
from choferes.models import Chofer


class ChoferesView(ListView):

    template_name = 'choferes/index.html'
    model = Chofer
    ordering = ('-created',)
    paginate_by = 30
    #context_object_name = 'posts'

class DetailChoferView(DetailView):

    model = Chofer
    template_name = 'choferes/view.html'
    #queryset = Post.objects.all()

class CreateChoferView(CreateView):

    model = Chofer
    form_class = ChoferForm
    template_name = 'choferes/create.html'
    success_url = reverse_lazy('choferes:list')

class UpdateChoferView(UpdateView):
    model = Chofer
    template_name = 'choferes/update.html'
    form_class = ChoferForm
    success_url = reverse_lazy('choferes:list')

class DeleteChoferView(DeleteView):

    model = Chofer
    form_class = ChoferForm
    success_url = reverse_lazy('choferes:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/choferes/create.html
{% extends "main.html" %}

{% block head_content %}
<title>Crear Trayectoria</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Registrar Chofer</h4>
        </div>
    </div>

    <div class="row">
        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
                <div class="input-field col s8">
                    <input id="rut" name="rut" type="text" class="validate">
                    <label for="rut">Rut</label>
                    <span class="red-text">{% for error in form.rut.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    <input id="nombre" name="nombre" type="text" class="validate">
                    <label for="nombre">Nombre</label>
                    <span class="red-text">{% for error in form.nombre.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    <input id="apellido" name="apellido" type="text" class="validate">
                    <label for="apellido">Apellido</label>
                    <span class="red-text">{% for error in form.apellido.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    <input id="telefono" name="telefono" type="text" class="validate">
                    <label for="telefono">Telefono</label>
                    <span class="red-text">{% for error in form.telefono.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <button type="submit" class="btn btn-primary  mt-5" value="Save">Guardar</button>
            <a href="/choferes" class="btn btn-primary  mt-2" >Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/choferes/index.html
{% extends "main.html" %}

{% block head_content %}
    <title>Destacame</title>
{% endblock%}

{% block container %}


        <div class="row">

            <div class="col s12">
                <h3>Listado Conductores</h3>
            </div>

            <div class="col s12">
                <a href='{% url "choferes:crear" %}' class="btn btn-primary  mt-2" >Registrar Conductor</a>
            </div>
        </div>

        <div class="divider"></div>
        <div class="row">
            <table class="table table-bordered" id="tb-choferes">
                <thead>
                    <tr>
                        <th>Rut</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Teléfono</th>
                        <th>Editado</th>
                        <th>Acciones</th>
                    </tr>
                    
                </thead>
                <tbody>
                    {% if object_list %}
                    {% for choferes in object_list %}
                    <tr>
                        <td>{{ choferes.rut }}</td>
                        <td>{{ choferes.nombre }}</td>
                        <td>{{ choferes.apellido }}</td>
                        <td>{{ choferes.telefono }}</td>
                        <td>{{ choferes.modified }}</td>
                        
                        <td>
                            <a class="btn btn-primary " href='{% url "choferes:detalle" choferes.pk %}'>Ver</a>
                            <a class="btn btn-primary" href='{% url "choferes:editar" choferes.pk %}'>Editar</a>
                            <a class="btn btn-danger btn-confirm" href='{% url "choferes:eliminar" choferes.pk %}'>Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                    {% else %}
                    <tr>
                        <td colspan="6">
                            <h4>No hay registros de conductores</h4>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>           
        </div>

{% endblock %}

templates/choferes/update.html
{% extends "main.html" %}

{% block head_content %}
<title>Crear Trayectoria</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Crear Chofer</h4>
        </div>
    </div>

    <div class="row">
        <form method="post" class="col s12">
            {% csrf_token %}

            <div class="row">
                <!--<h1>{{ object.rut }}</h1>-->
                <div class="input-field col s8">                    
                    {{form.rut}}
                    <label for="rut">Rut</label>
                    <span class="red-text">{% for error in form.rut.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    {{form.nombre}}
                    <label for="nombre">Nombre</label>
                    <span class="red-text">{% for error in form.nombre.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    {{form.apellido}}
                    <label for="apellido">Apellido</label>
                    <span class="red-text">{% for error in form.apellido.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s8">
                    {{form.telefono}}
                    <label for="telefono">Telefono</label>
                    <span class="red-text">{% for error in form.telefono.errors %}{{ error }}{% endfor %}</span>
                </div>
            </div>

            <button type="submit" class="btn btn-primary  mt-5" value="Save">Guardar</button>
            <a href="/choferes" class="btn btn-primary  mt-2" >Cancelar</a>
        </form>
    </div>
{% endblock %}

templates/choferes/view.html
{% extends "main.html" %}

{% block head_content %}
<title>Choferes</title>
{% endblock %}

{% block container %}

    <div class="row">
        <div class="col s12">
            <h4>Perfil {{ object.nombre }}</h4>
        </div>
    </div>

    <div class="row">

        <table>
            <tr>
                <td>
                    Rut
                </td>
                <td>
                    {{ object.rut }}
                </td>
            </tr>

            <tr>
                <td>
                    Nombre
                </td>
                <td>
                    {{ object.nombre }}
                </td>
            </tr>

            <tr>
                <td>
                    Apellido
                </td>
                <td>
                    {{ object.apellido }}
                </td>
            </tr>

            <tr>
                <td>
                    Telephono
                </td>
                <td>
                    {{ object.telefono }}
                </td>
            </tr>
        </table>

        <a href="/choferes" class="btn btn-primary  mt-2">Regresar</a>
        </form>
    </div>
{% endblock %}